apiVersion: v1
kind: Service
metadata:
  name: {{ include "manifest-service-admin.fullname" . }}
  labels:
    {{- include "manifest-service-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      containerPort: 6060
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http 
  selector:
    {{- include "manifest-service-admin.selectorLabels" . | nindent 4 }}
