{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manifest-service-admin.serviceAccountName" . }}
  labels:
{{ include "manifest-service-admin.labels" . | nindent 4 }}
{{- end -}}
