{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manifest-frontend.serviceAccountName" . }}
  labels:
{{ include "manifest-frontend.labels" . | nindent 4 }}
{{- end -}}
